on:
  push:
    branches:
      - main

name: Latest Snapshot

jobs:
  containerize:
    name: "Push Docker image to Docker Hub"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@v4"
        with:
          images: "someawesomedockerid/rocket-banking"

      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v3"
        with:
          context: .
          push: true
          tags: someawesomedockerid/rocket-banking:latest
          labels: ${{ steps.meta.outputs.labels }}
